### ISSUE TITLE
Tagging versions/releases

### ISSUE THREAD

**Issue by iugrina** [Tarskin/MassyTools#8]
It is a good practice to tag a commit with a version name. See [this](https://git-scm.com/book/en/Git-Basics-Tagging) for more info on how to tag commits. Check [this](https://help.github.com/articles/pushing-to-a-remote/) on how to push tags to github.

Since the last commit (d4967e4a934eed0acc7985495021f53eb1d33ee3) changed the version string I think this is a great time for you @Tarskin to tag a release :)

**Comment by Tarskin** [comment]
Do you know if GitHub supports a 'tag' in the code that is automatically replaced by the current version tag?

**Comment by Tarskin** [comment]
GitHub versions have been comitted for v0.1.8.0 (current) and v0.1.6.3.1 (publication version).

**Comment by iugrina** [comment]
You've become a pro :)

**Comment by Tarskin** [comment]
Thanks, I have to admit that it was quite fun to read about how Git keeps track of this. However, there is an issue that the v0.1.6.3.1 one is considered the latest release now *shrug*.
